export const ADD_ACHIEVEMENT = "ADD_ACHIEVEMENT";
export const REMOVE_ACHIEVEMENT = "REMOVE_ACHIEVEMENT";
export const NEXT_DATE = "NEXT_DATE";
export const PREV_DATE = "PREVIOUS_DATE";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_CALENDAR_VISIBILITY = "SET_CALENDAR_VISIBILITY";
export const SET_USER = "SET_USER";
export const GET_ACHIEVEMENTS = "GET_ACHIEVEMENTS";
