export const ADD_ACHIEVEMENT = "ADD_ACHIEVEMENT";
export const REMOVE_ACHIEVEMENT = "REMOVE_ACHIEVEMENT";
export const NEXT_DATE = "NEXT_DATE";
export const PREV_DATE = "PREVIOUS_DATE";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
