import { FC } from 'react';
import styled, { keyframes } from 'styled-components';

interface IProps {
  size?: number;
}

interface IInnerProps {
  size: number;
}

/* CSS generated by https://loading.io/ */
const spinnerAnimation = keyframes`
    0% { transform: translate(-50%,-50%) rotate(0deg); }
    100% { transform: translate(-50%,-50%) rotate(360deg); }
`;

const Container = styled.div`
  width: ${(props: IInnerProps) => `${props.size * 24}px`};
  height: ${(props: IInnerProps) => `${props.size * 24}px`};
  display: inline-block;
  overflow: hidden;
  vertical-align: middle;
`;

const Content = styled.div`
  width: 100%;
  height: 100%;
  position: relative;
  transform: ${(props: IInnerProps) =>
    `translateZ(0) scale(${props.size * 0.24})`};
  backface-visibility: hidden;
  transform-origin: 0 0;
`;

const Innner = styled.div`
  box-sizing: content-box;
  position: absolute;
  width: 50px;
  height: 50px;
  border: 10px solid ${({ theme }) => theme.colors.common.primary};
  border-top-color: transparent;
  border-radius: 50%;

  animation: ${spinnerAnimation} 1s linear infinite;
  top: 50px;
  left: 50px;
`;

export const Spinner: FC<IProps> = ({ size = 1 }) => (
  <Container size={size}>
    <Content size={size}>
      <Innner />
    </Content>
  </Container>
);
